### ISSUE TITLE
Name: `service` is a bad name.

### ISSUE THREAD

**Issue by pbrochar** [mpruvot/python_chess_app#10]
https://github.com/mpruvot/python_chess_app/blob/9a22b93faca5e7b7fc8a8d75bca898c75c7f34fe/api/chess_engine_api.py#L14C1-L14C29

We don't name things about their role in the code, like `function` is a bad function name, `model` is a bad Pydantic name for a model 😄

**Comment by mpruvot** [comment]
fixed
